# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/nbio',
                'doc_host': 'https://mcclellanio.github.io',
                'git_url': 'https://github.com/mcclellanio/nbio',
                'lib_path': 'nbio'},
  'syms': {'nbio.core': {'nbio.core.foo': ('core.html#foo', 'nbio/core.py')}}}
