"""Test of nbdev"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_nbio.ipynb.

# %% auto 0
__all__ = ['say_hello', 'foo']

# %% ../nbs/00_nbio.ipynb 1
def say_hello(to):
    "Say hello to somebody"
    return f'Hello {to}!'

# %% ../nbs/00_nbio.ipynb 4
def foo(): pass

# %% ../nbs/00_nbio.ipynb 5
test_eq(say_hello("Mike"), "Hello Mike!")
